version: "1"
rules:
  - base: master
    upstream: istio:master
    autoMerge: true
    autoMergeHardReset: false
  - base: release-1.4
    upstream: istio:release-1.4
    autoMerge: true
    autoMergeHardReset: false
