# Gateway config, and associated virtual services

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
{{- if $.Values.certManager.enabled }}
  - port:
      number: 443
      name: https-default
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: tls-cert
    hosts:
    - "*"
{{- end }}
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "prom.{{ .Values.domain }}"
    - "prom.local"
    - "grafana.{{ .Values.domain }}"
    - "grafana.local"
    - "kiali.{{ .Values.domain }}"
    - "kiali.local"
    - "tracing.{{ .Values.domain }}"
    - "tracing.local"
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana
  namespace: istio-system
spec:
  hosts:
  {{- if not (eq $.Values.domain "local") }}
  - "grafana.{{ .Values.domain }}"
  {{ end }}
  - "grafana.local"
  gateways:
  - istio-gateway
  http:
  - route:
    - destination:
        host: grafana.istio-system.svc.cluster.local
        port:
          number: 3000
---
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "grafana"
  namespace: istio-system
spec:
  host: grafana.istio-system.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali
  namespace: istio-system
spec:
  hosts:
  {{- if not (eq $.Values.domain "local") }}
  - "kiali.{{ .Values.domain }}"
  {{ end }}
  - "kiali.local"
  gateways:
  - istio-gateway
  http:
  - route:
    - destination:
        host: kiali.istio-system.svc.cluster.local
        port:
          number: 20001
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prom
  namespace: istio-system
spec:
  hosts:
  {{- if not (eq $.Values.domain "local") }}
  - "prom.{{ .Values.domain }}"
  {{ end }}
  - "prom.local"
  gateways:
  - istio-gateway
  http:
  - route:
    - destination:
        host: istio-prometheus.istio-prometheus.svc.cluster.local
        port:
          number: 9090
---
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "prom"
  namespace: istio-system
spec:
  host: istio-prometheus.istio-prometheus.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tracing
  namespace: istio-system
spec:
  hosts:
  {{- if not (eq $.Values.domain "local") }}
  - "tracing.{{ .Values.domain }}"
  {{ end }}
  - "tracing.local"
  gateways:
  - istio-gateway
  http:
  - route:
    - destination:
        host: tracing.istio-system.svc.cluster.local
        port:
          number: 80
---
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "tracing"
  namespace: istio-system
spec:
  host: tracing.istio-system.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
